### ISSUE TITLE
Could picFoam use spatially nonuniform magnetic field?

### ISSUE THREAD

**Issue by PengChen2016** [TFDzarm/picFoam#1]
Thanks for your open source work!
picFoam supports _a stationary magnetic field / a constant magnetic field_ now [1]. Whether B is **constant only in time**, or **const both in time and space**? 
If picFoam of the current version does not support a spatially non-uniform static magnetic field, do you have a plan to support it?
Since I have little knowledge about openFoam, could you please tell me the possible difficulties in enabling picFoam to support non-uniform magnetic fields? We would like to fork this repository and have a try in the second half of this year if you do not have the plan. (I have the knowledge about ES-PIC/MCC algorithm and code.)

[1] Kühn, Christoph, and Rodion Groll. "picFoam: An OpenFOAM based electrostatic Particle-in-Cell solver." Computer Physics Communications 262 (2021): 107853.

**Comment by chriskuehn** [comment]
Sorry, didn't see this up until now. B is only stationary in time. You can define any spatial non-uniform field you like. OpenFOAM has a solver called magneticFoam with which its possible to generate magnetic fields from permanent magnets. Sadly there is no tutorial for it in the OpenFOAM repo, but here is a discussion about its usage: https://www.cfd-online.com/Forums/openfoam-solving/95146-magneticfoam.html It is possible to map the B field calculated by magneticFoam to picFoam using the application mapFields (it included with OpenFOAM). There also tools like setFields which can be used to predefine a field.

**Comment by PengChen2016** [comment]
Thank you very much!
